[package]
name = "xp-layer"
version = "0.1.0"
edition = "2021"
rust-version = "1.80"
description = "Windows XP API translation / compatibility layer written in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/JereyBeni/xp-layer"
readme = "README.md"

[dependencies]
eframe = "0.29"
egui = "0.29"

[profile.release]
lto = true
codegen-units = 1
